/*
Actualització de la DB a partir de la versió 0.27
*/

ALTER TABLE CURS ADD estat char(1) NOT NULL DEFAULT 'A';
ALTER TABLE CURS DROP COLUMN butlleti_visible;
ALTER TABLE CURS DROP COLUMN finalitzat;

ALTER TABLE USUARI ADD email_ins VARCHAR(100);

ALTER TABLE CICLE_FORMATIU ADD actiu BIT NOT NULL DEFAULT 1;
ALTER TABLE MODUL_PROFESSIONAL ADD actiu BIT NOT NULL DEFAULT 1;
ALTER TABLE UNITAT_FORMATIVA ADD activa BIT NOT NULL DEFAULT 1;
